# role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "monitoring-api.fullname" . }}-pod-logs-reader
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
