# rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "monitoring-api.fullname" . }}-pod-logs-reader-binding
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: {{ include "monitoring-api.fullname" . }}-pod-logs-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ include "monitoring-api.serviceAccountName" . }}