name: Continuous_Integration

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build and Push docker image and Helm chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: iboommm/k8s-monitoring-api:${{ steps.package-version.outputs.current-version}}-${{github.sha}}

  # helm:
  #   name: Helm
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   env:
  #     GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
  #     CHART_DEPLOYMENT_REPO: wutthiwatth/iboommm-deployment
  #     CHART_DEPLOYMENT_BRANCH: main
  #     CHART_DEPLOYMENT_PROJECT: monitoring-tools

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Checkout chart deployment repo
  #       uses: actions/checkout@v3
  #       with:
  #         repository: ${{ env.CHART_DEPLOYMENT_REPO }}
  #         ref: ${{ env.CHART_DEPLOYMENT_BRANCH }}
  #         path: iboommm-deployment
  #         fetch-depth: 0
  #         token: ${{ env.GIT_TOKEN }}

  #     - name: Get version
  #       id: package-version
  #       uses: martinbeentjes/npm-get-version-action@v1.3.1
      
  #     - name: Edit deployment version
  #       uses: mikefarah/yq@master
  #       with:
  #         cmd: |
  #           yq e -i '.image.tag = "${{ steps.package-version.outputs.current-version}}-${{ github.sha }}"' 'iboommm-deployment/deployments/${{ env.CHART_DEPLOYMENT_PROJECT }}/values-dev.yaml'

  #     - name: Push new values.yaml
  #       run: |
  #         cd iboommm-deployment
  #         git config user.name iboommmBot
  #         git config user.email iboommm@live.com
  #         git add deployments/${{ env.CHART_DEPLOYMENT_PROJECT }}/values-dev.yaml
  #         git commit -m "Update ${{ env.CHART_DEPLOYMENT_PROJECT }} version ${{ steps.package-version.outputs.current-version}}-${{ github.sha }} to values-dev.yaml"
  #         git push
        